### ISSUE TITLE
Deal with erroneous GPS coordinates

### ISSUE THREAD

**Issue by tacarlson** [srophe/places#1]
Dayr al-Zafaran (place/69) is not in Iran.

**Comment by davidamichelson** [comment]
Can you figure out why that is happening?

**Comment by tacarlson** [comment]
It's part of the original data from AWMC apparently.  Creating a ticket for it here allows ppl to add pointers to places with erroneous GPS coordinates as they find them.  I would recommend just deleting these coordinates as we find them, since they are not really asserted by the print GEDSH in any form.  I don't know how they got into the AWMC data while the GEDSH print maps still show them in the right place.

**Comment by davidamichelson** [comment]
Interesting, we could ask AWMC if we want to.

**Comment by tacarlson** [comment]
Decided simply to delete erroneous latitude and longitude from AWMC because we're the only consumer of that data.
