### ISSUE TITLE
add more structure to titles

### ISSUE THREAD

**Issue by paregorios** [srophe/places#2]
At present, the title element in the tei header for each place seems to contain a bare string that incorporates both Roman and Syriac characters in our usual style. Request the addition of more markup inside the titles so that we can act in XSLT and downstream HTML+CSS upon Syriac and "English" separately as we do elsewhere (e.g., assign different fonts). 

For example, place 5 current has the following code (I have collapsed unimportant whitespace): 

``` xml
<title level="a" xml:lang="en">Adharbayjān (region) — ܐܕܪܒܝܓܐܢ</title>
```

I'd like to suggest we replace this with something like the following:

``` xml
<title level="a" xml:lang="en">Adharbayjān (region) — 
    <foreign xml:lang="syr">ܐܕܪܒܝܓܐܢ</foreign></title>
```

This is needed in order to clear

**Comment by paregorios** [comment]
this is a blocker for https://github.com/srophe/srp-places-app/issues/54

**Comment by tacarlson** [comment]
I think I have done this successfully.  I am not familiar with standard workflow protocol, but I did this and pushed the new TEI records to the repo, and shortly I shall remove the blocked tag from srophe/srp-places-app#54.

**Comment by paregorios** [comment]
Looks great! Thanks.
