### ISSUE TITLE
add more structure to licence element

### ISSUE THREAD

**Issue by paregorios** [srophe/places#3]
In https://github.com/srophe/srp-places-app/issues/34 @davidamichelson envisions a nicely structured copyright and license statement in HTML, but the structure of the current licence element in the TEI files is insufficient to support the desired output. Request that additional structure be added in order to get the desired effect. 

For example, in place 5 we find (insignificant whitepace has been normalized):

``` xml
<licence target="http://creativecommons.org/licenses/by/3.0/"> Distributed under a
   Creative Commons Attribution 3.0 Unported License. This entry incorporates
   copyrighted material from the following work(s): I.A. Barsoum, The Scattered
   Pearls, © 1991 Bar Hebraeus Verlag (used under a Creative Commons Attribution
   license: http://creativecommons.org/licenses/by/3.0/). </licence>
```

This is all have been able to do with that in HTML:

![license](https://f.cloud.github.com/assets/263285/865604/2cf524dc-f63e-11e2-963e-e8dbe39e851b.png)

I think what DM wants can be added in some way like this:

``` xml
<licence target="http://creativecommons.org/licenses/by/3.0/">
   <p>Licensed for reuse under a Creative Commons Attribution 3.0 Unported License.</p>
   <p>This entry incorporates copyrighted material from the following work(s): 
      <listBibl>
         <bibl>
            <ptr target="http://syriaca.org/bibl/4"/>
            <note>used under a Creative Commons Attribution license: http://creativecommons.org/licenses/by/3.0/</note>.
         </bibl>
      </listBibl>
   </p>
</licence>
```

Wouild something like that be possible? Note the use of the ptr element inside the bibl, rather than repeating all the information (unless you feel you need the information in the file itself, in which case you might try the following alternative):

``` xml
<bibl>
    <ptr target="#bib5-4"/>
    <note>used under a Creative Commons Attribution license: http://creativecommons.org/licenses/by/3.0/</note>
</bibl>
```

which would keep the pointer reference internal to the file.

**Comment by paregorios** [comment]
This is a blocker for https://github.com/srophe/srp-places-app/issues/55

**Comment by paregorios** [comment]
it occurs to me that we might also want to wrap the license URL inside the note inside the bibl inside its own "ref" or "ptr" element so that we can easily make it an actionable link via XSLT without doing any string parsing.

**Comment by tacarlson** [comment]
How does the new data look?  I think I added all of the requested markup, but I put the &lt;note> which contains the CC-BY 3.0 license reference outside the &lt;listBibl> to avoid repeating it where we have used multiple works from Bar Hebraeus Verlag.  See an example such as place/5 or place/78.  If this looks good, please close this issue and unblock the srp-places-app issue blocked by this.

**Comment by paregorios** [comment]
looks good! closing.

**Comment by davidamichelson** [comment]
@paregorios, can we discuss this briefly on wednesday? I am wondering about
the attribution and license data, will this scale if we have different
kinds of licences (or we may exclude that data) and do we need to include
the specific attribution language in the bibl.xml file?
