### ISSUE TITLE
invalid ref atttribute in 1187.xml

### ISSUE THREAD

**Issue by paregorios** [srophe/places#4]
At https://github.com/srophe/places/blob/master/xml/1187.xml#L88 we find:

``` xml
<settlement ref="http://syriaca.org/place/ district-1231">Mār Sābā sub</settlement>
```

which has an invalid value for the ref attribute. This is the underlying cause of https://github.com/srophe/srp-places-app/issues/60 .

**Comment by tacarlson** [comment]
Right, sorry about that!  Using '-' as a separator character when it also occurs in a place name...  I'll fix this tomorrow.

**Comment by tacarlson** [comment]
I think this is now fixed.  I changed my delimiter string to a string not found in any place name.  Let me know if you find any more like this in the current data (just pushed a new batch).
