### ISSUE TITLE
Github links at bottom of place page do not load file number

### ISSUE THREAD

**Issue by davidamichelson** [srophe/places#6]
For some reason, the TEi link on place 78 html page works in the upper corner but not in the see also list where it resolves to: https://github.com/srophe/places/blob/master/xml/.xml

Thanks!
Dave

**Comment by tacarlson** [comment]
This is a duplicate of srophe/srp-places-app#120 .

**Comment by wsalesky** [comment]
Is this something you would like fixed now, or in the new version?

**Comment by davidamichelson** [comment]
No it can wait for the new version. Sorry for not realizing it already had
a ticket.

**Comment by wsalesky** [comment]
@davidamichelson stale issue.
